### ISSUE TITLE
Improve documentation in the Readme

### ISSUE THREAD

**Issue by tim-kos** [transloadit/go-sdk#18]
I think the readme lacks quite a bit of documentation for all the available public methods. An example would be https://github.com/transloadit/node-sdk

It would be nice if the Readme also included where a template is used.

**Comment by kvz** [comment]
Talked some more about this and we agree that, without duplicating https://godoc.org/github.com/transloadit/go-sdk into this project's README.md, adding a near-copy-pastable example for adding a template would be a cool addition.
