### ISSUE TITLE
failed execute http request:

### ISSUE THREAD

**Issue by yhyddr** [transloadit/go-sdk#25]
![image](https://user-images.githubusercontent.com/32089134/65813142-a145db80-e203-11e9-8e4a-b6174ea3eaea.png)

**Comment by yhyddr** [comment]
now I success but I could not visit this url
You can view the result at https://s3-ap-southeast-1.amazonaws.com/tmp-ap-southeast-1.transloadit.com/1e3a834905904c0c935d0ccdc1552834.jpg
![image](https://user-images.githubusercontent.com/32089134/65813425-a147da80-e207-11e9-9415-6abb7f4ac78e.png)

**Comment by Acconut** [comment]
Does the URL now work for you? I get an image when going to https://s3-ap-southeast-1.amazonaws.com/tmp-ap-southeast-1.transloadit.com/1e3a834905904c0c935d0ccdc1552834.jpg Could it be that you had network connection issues?

**Comment by yhyddr** [comment]
It's truly network connection, cause I'm in china.Thanks
